modLoader="javafml"
loaderVersion="[43,)"
license="LGPLv3"
issueTrackerURL="https://github.com/yungnickyoung/YUNGs-Better-Nether-Fortresses/issues"

[[mods]]
    modId="betterfortresses"
    version="${file.jarVersion}"
    displayName="YUNG's Better Nether Fortresses"
    credits="Thanks so much to all my patrons!"
    authors="YUNGNICKYOUNG, Acarii"
    description="A complete redesign of Minecraft's Nether Fortresses!"
    logoFile="logo.png"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/yungs-better-nether-fortresses"

[[dependencies.betterfortresses]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"

[[dependencies.betterfortresses]]
    modId="forge"
    mandatory=true
    versionRange="[43.1.1,)"

[[dependencies.betterfortresses]]
    modId="yungsapi"
    versionRange="[1.19.2-Forge-3.5.0,)"
    mandatory=true
    ordering="NONE"
    side="BOTH"